{
  "headers": {
    "client_id": "123",
    "client_secret": "563",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "b9d4787f-176d-42d8-8adc-b9ed3fdc1c4d",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "148"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/registerAdmin",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/registerAdmin",
  "listenerPath": "/api/*",
  "relativePath": "/api/registerAdmin",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/registerAdmin",
  "rawRequestPath": "/api/registerAdmin",
  "remoteAddress": "/127.0.0.1:58503",
  "requestPath": "/api/registerAdmin"
}